# docker-compose.yml for Jules Endpoint Agent
#
# This file simplifies the process of running the agent in a Docker container.
#
version: '3.8'

services:
  jules-agent:
    # Build the image using the repo root as the context.
    build:
      context: ..
      dockerfile: docker/Dockerfile
    # Name the container for easier management.
    container_name: jules-agent
    # Restart the container automatically if it stops.
    restart: unless-stopped
    # Expose the SSH port to the host machine. Mapping to 2222 on the host
    # to avoid potential conflicts with the host's own SSH service.
    ports:
      - "2222:22"
    # Environment variables required by the agent.
    # IMPORTANT: You must fill in these values before running!
    environment:
      # Get this token from the Cloudflare Zero Trust dashboard.
      # It's a long string that authorizes the tunnel.
      - CLOUDFLARE_TOKEN=YOUR_CLOUDFLARE_TOKEN_HERE
      # Paste the AI agent's PUBLIC SSH key here.
      # The agent will use its private key to authenticate.
      - JULES_SSH_PUBLIC_KEY=ssh-rsa ... your_agent_public_key

    # --- GPU Acceleration (Optional) ---
    # Uncomment the following section if you have an NVIDIA GPU and have installed
    # the NVIDIA Container Toolkit on your host machine.
    # This gives the container access to the host's GPU for hardware acceleration.
    #
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
