# docker-compose.yml for Jules Endpoint Agent
#
# This file simplifies the process of running the agent in a Docker container.
#

services:
  jules-agent:
    # Build the image using the repo root as the context.
    build:
      context: ..
      dockerfile: docker/Dockerfile
    # Name the container for easier management.
    container_name: jules-agent
    # Restart the container automatically if it stops.
    restart: unless-stopped
    # Health check configuration
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Expose the SSH port to the host machine. Mapping to 2222 on the host
    # to avoid potential conflicts with the host's own SSH service.
    ports:
      - "2222:22"
    # Environment variables required by the agent.
    # IMPORTANT: You must fill in these values in the .env file before running!
    environment:
      - CLOUDFLARE_TOKEN=${CLOUDFLARE_TOKEN}
      - JULES_SSH_PUBLIC_KEY=${JULES_SSH_PUBLIC_KEY}
      - SSH_PORT=${SSH_PORT:-22}
      - JULES_USERNAME=${JULES_USERNAME:-jules}

    # --- GPU Acceleration (Optional) ---
    # Uncomment the following section if you have an NVIDIA GPU and have installed
    # the NVIDIA Container Toolkit on your host machine.
    # This gives the container access to the host's GPU for hardware acceleration.
    #
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    
    # --- Hardware Access Configuration ---
    # Enable privileged mode for full hardware access (commented out for initial setup)
    # privileged: true
    
    # Basic volume mounts
    volumes:
      - jules-data:/home/jules
    
    # Additional capabilities for basic operations
    cap_add:
      - SYS_ADMIN

volumes:
  jules-data:
